/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      animation: {
        'slide-down': 'slide-down 0.3s ease-out',
        'slide-up': 'slide-up 0.5s ease-out',
        'move-from-right': 'move-from-right 0.3s ease-out',
        'move-from-bottom': 'move-from-bottom 0.3s ease-out',
        'messagge-from-right': 'messagge-from-right 0.3s ease-out',
        'forms-from-right': 'forms-from-right 0.3s ease-out',
        'move-from-right-form': 'move-from-right-form 0.25s ease-out',
        'move-from-right-form-2': 'move-from-right-form-2 0.25s ease-out',
        'user-menu': 'user-menu 0.1s ease-out',
        'breathe': 'breathe 1s infinite ease-in-out',
        'modal-appointment': 'modal-appointment 0.2s ease-in',
        'alredy-exists': 'alredy-exists 0.1s ease-out',
      },
      keyframes: {
        'slide-down': {
          '0%': { opacity: '1', transform: 'translateY(-100%)' },
          '25%': { opacity: '1', transform: 'translateY(-75%)' },
          '50%': { opacity: '1', transform: 'translateY(-50%)' },
          '75%': { opacity: '1', transform: 'translateY(-25%)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { opacity: '1', transform: 'translateY(0%)' },
          '25%': { opacity: '1', transform: 'translateY(-25%)' },
          '50%': { opacity: '1', transform: 'translateY(-50%)' },
          '75%': { opacity: '1', transform: 'translateY(-75%)' },
          '100%': { opacity: '1', transform: 'translateY(-100%)' },
        },
        'move-from-right': {
          '0%': { opacity: '1', transform: 'translateX(50%)' },
          '10%': { opacity: '1', transform: 'translateX(35%)' },
          '20%': { opacity: '1', transform: 'translateX(20%)' },
          '30%': { opacity: '1', transform: 'translateX(5%)' },
          '40%': { opacity: '1', transform: 'translateX(0%)' },
          '50%': { opacity: '1', transform: 'translateX(-10%)' },
          '60%': { opacity: '1', transform: 'translateX(-5%)' },
          '70%': { opacity: '1', transform: 'translateX(0%)' },
          '80%': { opacity: '1', transform: 'translateX(10%)' },
          '90%': { opacity: '1', transform: 'translateX(5%)' },
          '100%': { opacity: '1', transform: 'translateX(0%)' },
        },
        'move-from-bottom': {
          '0%': { opacity: '1', transform: 'translateY(50%)' },
          '10%': { opacity: '1', transform: 'translateY(35%)' },
          '20%': { opacity: '1', transform: 'translateY(20%)' },
          '30%': { opacity: '1', transform: 'translateY(5%)' },
          '40%': { opacity: '1', transform: 'translateY(0%)' },
          '50%': { opacity: '1', transform: 'translateY(-10%)' },
          '60%': { opacity: '1', transform: 'translateY(-5%)' },
          '70%': { opacity: '1', transform: 'translateY(0%)' },
          '80%': { opacity: '1', transform: 'translateY(10%)' },
          '90%': { opacity: '1', transform: 'translateY(5%)' },
          '100%': { opacity: '1', transform: 'translateY(0%)' },
        },
        'messagge-from-right': {
          '0%': { opacity: '0', transform: 'translateX(40%)' },
          '15%': { opacity: '0.1', transform: 'translateX(20%)' },
          '30%': { opacity: '1', transform: 'translateX(10%)' },
          '45%': { opacity: '1', transform: 'translateX(7%)' },
          '60%': { opacity: '1', transform: 'translateX(5%)' },
          '75%': { opacity: '1', transform: 'translateX(3%)' },
          '90%': { opacity: '1', transform: 'translateX(1%)' },
          '100%': { opacity: '1', transform: 'translateX(0%)' },
        },
        'forms-from-right': {
          '0%': { transform: 'translateX(40%)' },
          '15%': { transform: 'translateX(20%)' },
          '30%': { transform: 'translateX(10%)' },
          '45%': { transform: 'translateX(7%)' },
          '60%': { transform: 'translateX(5%)' },
          '75%': { transform: 'translateX(3%)' },
          '90%': { transform: 'translateX(1%)' },
          '100%': { transform: 'translateX(0%)' },
        },
        'move-from-right-form': {
          '0%': { opacity: '1', transform: 'translateX(100%)' },
          '10%': { opacity: '1', transform: 'translateX(90%)' },
          '20%': { opacity: '1', transform: 'translateX(80%)' },
          '30%': { opacity: '1', transform: 'translateX(70%)' },
          '40%': { opacity: '1', transform: 'translateX(60%)' },
          '50%': { opacity: '1', transform: 'translateX(50%)' },
          '60%': { opacity: '1', transform: 'translateX(40%)' },
          '70%': { opacity: '1', transform: 'translateX(30%)' },
          '80%': { opacity: '1', transform: 'translateX(20%)' },
          '90%': { opacity: '1', transform: 'translateX(10%)' },
          '100%': { opacity: '1', transform: 'translateX(0%)' },
        },
        'move-from-right-form-2': {
          '0%': { opacity: '1', transform: 'translateX(100%)' },
          '10%': { opacity: '1', transform: 'translateX(90%)' },
          '20%': { opacity: '1', transform: 'translateX(80%)' },
          '30%': { opacity: '1', transform: 'translateX(70%)' },
          '40%': { opacity: '1', transform: 'translateX(60%)' },
          '50%': { opacity: '1', transform: 'translateX(50%)' },
          '60%': { opacity: '1', transform: 'translateX(40%)' },
          '70%': { opacity: '1', transform: 'translateX(30%)' },
          '80%': { opacity: '1', transform: 'translateX(20%)' },
          '90%': { opacity: '1', transform: 'translateX(10%)' },
          '100%': { opacity: '1', transform: 'translateX(0%)' },
        },
        'user-menu': {
          '0%': { opacity: '1', transform: 'translateY(-20%)' },
          '25%': { opacity: '1', transform: 'translateY(-15%)' },
          '50%': { opacity: '1', transform: 'translateY(-10%)' },
          '75%': { opacity: '1', transform: 'translateY(-5%)' },
          '100%': { opacity: '1', transform: 'translateY(0%)' },
        },
        'breathe': {
          '0%': { opacity: '0.8' },
          '50%': { opacity: '0.3' },
          '100%': { opacity: '0.8' },
        },
        'modal-appointment': {
          '0%': { opacity: '0.1', transform: 'translateY(-50%)' },
          '8.33%': { opacity: '0.2', transform: 'translateY(-40%)' },
          '16.66%': { opacity: '0.3', transform: 'translateY(-30%)' },
          '25%': { opacity: '0.4', transform: 'translateY(-20%)' },
          '33.33%': { opacity: '0.5', transform: 'translateY(-10%)' },
          '41.66%': { opacity: '0.5', transform: 'translateY(0%)' },
          '50%': { opacity: '0.7', transform: 'translateY(10%)' },
          '58.33%': { opacity: '0.8', transform: 'translateY(10%)' },
          '66.66%': { opacity: '1', transform: 'translateY(7%)' },
          '75%': { opacity: '1', transform: 'translateY(3%)' },
          '87.5%': { opacity: '1', transform: 'translateY(0%)' },
          '100%': { opacity: '1', transform: 'translateY(0%)' },
        },
        'alredy-exists': {
          '0%': { opacity: '0.4', transform: 'translateY(60%)' },
          '8.33%': { opacity: '0.4', transform: 'translateY(50%)' },
          '16.66%': { opacity: '0.4', transform: 'translateY(40%)' },
          '25%': { opacity: '0.4', transform: 'translateY(30%)' },
          '33.33%': { opacity: '0.5', transform: 'translateY(20%)' },
          '41.66%': { opacity: '0.5', transform: 'translateY(10%)' },
          '50%': { opacity: '0.7', transform: 'translateY(0%)' },
          '58.33%': { opacity: '0.8', transform: 'translateY(-10%)' },
          '66.66%': { opacity: '1', transform: 'translateY(-20%)' },
          '75%': { opacity: '1', transform: 'translateY(-10%)' },
          '87.5%': { opacity: '1', transform: 'translateY(0%)' },
          '100%': { opacity: '1', transform: 'translateY(0%)' },
        },
      },
    },
  },
  plugins: [],
}
